import * as React from 'react';
import type { Metadata } from "next";
import "./ui/globals.css";

import Stack from '@mui/joy/Stack';
import Box from '@mui/joy/Box';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import TopNav from "@/app/topnav"
import {Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                        children,
                                      }: Readonly<{
                                        children: React.ReactNode;
                                      }>) {
  return (
    <html lang="en">
    <head>
    <title> Re-veal dubai</title>
    </head>
      <body >
        <Stack spacing={2} sx={{  width: '100%', alignItems: 'left'}}>
          <TopNav/>
          <Toaster position="top-right" expand={true} richColors/>
          <Box sx={{paddingLeft:1}}>
          {children}
          </Box>
          </Stack>
          
      </body>
    </html>
  );
}
